## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

baseURL = "https://www.vofgiftersig.se"
title = "Vof gifter sig"
languageCode = "sv-se"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
#  github = "https://github.com/caressofsteel/"
#  twitter = "https://twitter.com/caressofsteel_"
  email = "spexmonolog@vofgiftersig.se"
  instagram = "https://instagram.com/explore/tags/vofgiftersig"
#  linkedin = "https://linkedin.com"
#  telegram = "https://telegram.org"